namespace NF.UnityLibs.Managers.PatchManagement
{
    public enum E_PATCH_STATE
    {
        NONE = 0,
        RECIEVE_PATCHBUILDVERSION_START = 100,
        RECIEVE_PATCHBUILDVERSION_END = 200,
        PATCHFILELIST_CURR = 300,
        PATCHFILELIST_NEXT = 400,
        PATCHFILELIST_DIFF_COLLECT_START = 500,
        PATCHFILELIST_DIFF_COLLECT_END = 600,
        PATCHFILELIST_VALIDATE = 700,
        PATCHFILELIST_FINALIZE = 800,
    }
}