namespace NF.UnityLibs.Managers.PatchManagement
{
    public enum E_EXCEPTION_KIND
    {
        ERR_WEBREQUEST_TXT_IS_EMPTY,
        ERR_WEBREQUEST_FAIL,
        ERR_APPLICATION_IS_NOT_PLAYING,
        ERR_NETWORK_IS_NOT_REACHABLE,
        ERR_TASK_IS_CANCELED,
        ERR_FAIL_OPTION_VALIDATE,
        ERR_FAIL_TO_GET_PATCHBUILDVERSION,
        ERR_SYSTEM_EXCEPTION,
        ERR_LACK_OF_STORAGE,
        ERR_FAIL_TO_VALIDATE_PATCHFILES
    }
}
